# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e1bc544a08d2aae70372f022ba86666dd7b9a833f48ee2a7c3258cae15fa40e6cd32fd41b46c9948e00446249f9de078f4d06ee293d1c5ecb0b3a2024ed1a9fd

test:
  secret_key_base: f50550385c3bae18fa4eb9914a5e872515a54cfc6eb677ae2b2d6e13116c51852feea15c2689d080ce24c8ecec468b93c8965b3cba2d7964ceb8d838f6866cb5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>